#!/usr/bin/env ruby

require 'optparse'
require_relative 'main'

PROGRAM_NAME = File.basename($PROGRAM_NAME)
CFG_FILENAME = '.episode'

options = {}
opt_parser = 
  OptionParser.new do |opts|
    opts.program_name = PROGRAM_NAME
    opts.version = '0.1'
    opts.banner = <<~EOS
    Usage: #{PROGRAM_NAME} [options] <command> 

      Quick start:
        ep ls     show episodes in current directory with their indexes
        ep 7      play episode #7
        ep next   play next episode (or first)

      Commands:
        (l) last                  Re-play episode watched last time 
        (n) next                  Play next episode
        (p) prev                  Play previous episode (one before 'last') 
            <number>              Same as `#{PROGRAM_NAME} no <number>` (i.e. `#{PROGRAM_NAME} 11`)
            no                    Play episode by number (i.e. `#{PROGRAM_NAME} no 11`) 
        (c) cfg                   Display config for current directory
        (r) reset [param]         Reset config parameter (i.e. `#{PROGRAM_NAME} reset last`)
        (s) set <param> <value>   Set config parameter (i.e. `#{PROGRAM_NAME} set last 11`)
            ls                    List all episodes

      Options for last, next, prev, and no:
    EOS

    opts.on('-n', '--name', "Show episode name, but don't play it (i.e. `#{PROGRAM_NAME} -n 11`)") do
      options[:name] = true
    end
    
    opts.on('-o', '--no-update', "Don't update .episode file") do
      options[:update] = false
    end
  end
opt_parser.parse!

unless ARGV[0] 
  $stderr.puts opt_parser.help
  return
end

if ARGV[0] =~ /^\d+$/
  command = 'no'
  args = [ARGV[0]]
else
  command = ARGV[0]
  args = ARGV[1..]
end

begin    
  Main.new(options).send(command, *args)
rescue NoCommandError => e
  $stderr.puts <<~EOS
    Error: Unknown command '#{e.message}'. 
    Run `#{PROGRAM_NAME} -h` to see the list of all available commands.
  EOS
rescue CommandError => e
  $stderr.puts e.message
end
